mysite/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    # path("login/", views.user_login, name="user_login"),
    # django 内置登录方法
    path("login/", auth_views.LoginView.as_view(template_name='account/login2.html'), name="user_login"),
    # 在Django中，默认配置了登录之后页面的转向地址，在官方文档中对此有明确说明。即LOGIN_REDIRECT_URL的默认值是
    # /account/profile/ 为了设置项目所需要的转向目标，需要在settings中增加LOGIN_REDIRECT_URL 的值
    # Django 内置退出方法
    path("logout/", auth_views.LogoutView.as_view(template_name='account/logout.html'), name="user_logout"),
    path("register/", views.register, name="user_register"),
    path("password-change/", auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html",
                                                                   success_url="/account/password-change-done/"),
         name="password_change"),
    path("password-change-done/",
         auth_views.PasswordChangeDoneView.as_view(template_name="account/password_change_done.html"),
         name="password_change_done"),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html",
                                                                 email_template_name="account/password_reset_email.html",
                                                                 success_url="/account/password-reset-done/"),
         name="password_reset"),
    # email_template_name :设置向申请重置密码的用户邮箱所发送的邮件内容
    path("password-reset-done/", auth_views.PasswordResetDoneView.as_view
            (template_name="account/password_reset_done.html"), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view
        (template_name="account/password_reset_confirm.html",success_url="/account/password-reset-complete/"),
         name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view
    (template_name="account/password_reset_complete.html"),name="password_reset_complete"),
    path("my-information/",views.myself,name="my_information"),
    path("edit-my-information/",views.myself_edit,name="edit_my_information"),
    path("my-image/",views.my_image,name="my_image"),



]


mysite/article/urls.py
from django.urls import path,re_path
from . import views,list_views

app_name = "article"

urlpatterns = [
    path("article-column/",views.article_column,name="article_column"),
    path("rename-column/",views.rename_article_column,name="rename_article_column"),
    path("del-column/",views.del_article_column,name="del_article_column"),
    path("article-post/",views.article_post, name="article_post"),
    path("article-list/",views.article_list,name='article_list'),
    re_path("article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$", views.article_detail, name='article_detail'),
    path("del-article/",views.del_article,name="del_article"),
    path("redit-article/<int:article_id>/",views.redit_article,name="redit_article"),
    path("list-article-titles/",list_views.article_titles,name="article_titles"),
    path("article-content/<int:id>/<slug:slug>/",list_views.article_detail,name="article_content"),
    path("list-article-titles/<username>/",list_views.article_titles,name="author_articles"),
    path("like-article/",list_views.like_article,name="like_article"),
    path("article-tag/",views.article_tag,name="article_tag"),
    path("del-article-tag/",views.del_article_tag,name="del_article_tag"),



]

mysite/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"  # 方式二需要加此项
urlpatterns = [
    path("", views.blog_title, name="blog_title"),
    path('<int:article_id>/', views.blog_article, name="blog_article"),

]

mysite/course/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import AboutView,CourseListView,ManageCourseListView
from .views import CreateCourseView,DeleteCourseView,CreateLessonView
from .views import ListLessonsView,DetailLessonView,StudentListLessonView,LessonDetailView

app_name = "course"

urlpatterns =[
    # path('about/',TemplateView.as_view(template_name="course/about.html")),
    path('about/',AboutView.as_view(),name="about"),
    path('course-list/',CourseListView.as_view(),name="course_list"),
    path('manage-course/',ManageCourseListView.as_view(),name='manage_course'),
    path('create-course/',CreateCourseView.as_view(),name="create_course"),
    path('delete-course/<int:pk>/',DeleteCourseView.as_view(),name="delete_course"),
    path('create-lesson/',CreateLessonView.as_view(),name="create_lesson"),
    path('list-lessons/<int:course_id>/',ListLessonsView.as_view(),name="list_lessons"),
    path('detail-lesson/<int:lesson_id>/',DetailLessonView.as_view(),name="detail_lesson"),
    path('lessons-list/<int:course_id>/',StudentListLessonView.as_view(),name="lessons_list"),
    path('lesson-detail/<int:lesson_id>',LessonDetailView.as_view(),name="lesson_detail"),

]

mysite/image/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'image'

urlpatterns = [
    path('list-images/',views.list_images,name='list_images'),
    path('upload-image/',views.upload_image, name='upload_image'),
    path('del-image/',views.del_image,name='del_image'),
    path('images/',views.falls_images,name='falls_images'),


]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

# 为上传的图片配置url路径(1)
from django.conf import settings
from django.conf.urls.static import static
# 通用视图
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # 为了实现{% url 'blog:blog_title' %}的效果，需要在项目和应用两级的urls.py文件进行相应配置
    # path('blog/',include(('blog.urls', 'blog'), namespace='blog')),   # 方式一

    path('blog/', include('blog.urls', namespace='blog')),      # 方式二
    path('account/', include('account.urls', namespace='account')),
    path('article/',include('article.urls',namespace='article')),
    path('home/', TemplateView.as_view(template_name='home.html'),name='home'),
    path('image/', include('image.urls',namespace='image')),
    path('course/',include('course.urls',namespace='course')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!--<link rel="stylesheet" href="https://github.com/necolas/normalize.css/blob/master/normalize.css">-->
    <!--<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
    <!--<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>-->

</body>
</html>

mysite/templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.baidu.com</p>
</div>

mysite/templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="https://yz.chsi.com.cn/apply/cjcx/">
                <img src="{% static '/img/logos.png' %}" width="80px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'home' %}">Home</a> </li>
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
                <li><a href="{% url 'article:article_titles' %}">文章</a> </li>
                <li><a href="{% url 'image:falls_images' %}">图片展示</a> </li>
                <li><a href="{% url 'course:course_list' %}">课程</a> </li>
                <li><a href="{% url 'course:about' %}">关于本站</a> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px;">
                {% if user.is_authenticated %}
                <!--视图函数并没有直接返回user对象，返回request，从request中获取user-->
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu"
                                data-toggle="dropdown">
                            {{ user.username }}
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'account:password_change' %}">修改密码</a>
                            </li>
                            <li>
                                <a href="{% url 'account:my_information' %}">个人信息</a>
                            </li>
                            <li>
                                <a href="{% url 'article:article_column' %}">后台管理</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <!--<li><a href="#">{{ user.username }}</a> </li>-->
                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                <li><a href="{% url 'account:user_register' %}">Sign up</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<!--<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>-->
<script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<!--<script src="https://cdn.bootcss.com/bootstarp/3.3.7/js/bootstrap.min.js"></script>-->
<script src="{% static 'js/bootstrap.js' %}"></script>

mysite/templates/home.html
{% extends "base.html" %}
{% block title %}Home page{% endblock %}
{% block content %}
<div class="text-center">
    <h1>Welcome ZX Blog</h1>
    {% load staticfiles %}
    <img src="{% static 'img/home.jpg' %}" width="1150px">
</div>

{% endblock %}

mysite/templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page{{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>