mysite/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"  # 方式二需要加此项
urlpatterns = [
    path("", views.blog_title, name="blog_title"),
    path('<int:article_id>/', views.blog_article, name="blog_article"),

]

mysite/image/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'image'

urlpatterns = [
    path('list-images/',views.list_images,name='list_images'),
    path('upload-image/',views.upload_image, name='upload_image'),
    path('del-image/',views.del_image,name='del_image'),
    path('images/',views.falls_images,name='falls_images'),


]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

# 为上传的图片配置url路径(1)
from django.conf import settings
from django.conf.urls.static import static
# 通用视图
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # 为了实现{% url 'blog:blog_title' %}的效果，需要在项目和应用两级的urls.py文件进行相应配置
    # path('blog/',include(('blog.urls', 'blog'), namespace='blog')),   # 方式一

    path('blog/', include('blog.urls', namespace='blog')),      # 方式二
    path('account/', include('account.urls', namespace='account')),
    path('article/',include('article.urls',namespace='article')),
    path('home/', TemplateView.as_view(template_name='home.html'),name='home'),
    path('image/', include('image.urls',namespace='image')),
    path('course/',include('course.urls',namespace='course')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/image/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from slugify import slugify


class Image(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="images")
    title = models.CharField(max_length=300)
    url = models.URLField()
    slug = models.SlugField(max_length=500,blank=True)
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,db_index=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d')

    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(Image, self).save(*args,**kwargs)

mysite/image/forms.py
from django import forms
from django.core.files.base import ContentFile
from slugify import slugify
from urllib import request

from .models import Image


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title','url','description')

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg','jpeg','png'] # 规定图片的扩展名
        extension = url.rsplit('.',1)[1].lower()  # 从得到图片的网址中分解出其扩展名
        if extension not in valid_extensions:   # 如果属于规定的扩展名，就认为提交的URL对象是一个图片
            raise forms.ValidationError('The given url does not match valid image extension.')
        return url

    def save(self,force_insert=False,force_update=False,commit=True):
        # ModelForm类中的save方法，将表单提交的数据保存到数据库
        image = super(ImageForm, self).save(commit=False)  # 执行父类ModelForm的save()方法，commit=False实例虽然被建立，但并没有保存数据
        image_url = self.cleaned_data['url']
        image_name = '{0}.{1}'.format(slugify(image.title),image_url.rsplit('.',1)[1].lower())
        response = request.urlopen(image_url)  # 以get方式访问该图片地址 ，通过该对象得到所访问URL的数据（图片的ASCII）
        image.image.save(image_name, ContentFile(response.read()),save=False) #　将上述返回的结果保存到本地，并按照约定的名称给该图片文件命名
        if commit:
            image.save()
        return image

mysite/image/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from .forms import ImageForm
from .models import Image


@login_required(login_url="/account/login/")
@csrf_exempt
@require_POST
def upload_image(request):
    form = ImageForm(data=request.POST)
    if form.is_valid():
        try:
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            return JsonResponse({'status': '1'})
        except:
            return JsonResponse({'status': '0'})
    else:
        print("tijiao buhefa ")


@login_required(login_url='/account/login/')
def list_images(request):
    images = Image.objects.filter(user=request.user)
    return render(request,'image/list_images.html',{"images":images})


@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def del_image(request):
    image_id = request.POST['image_id']
    try:
        image = Image.objects.get(id=image_id)
        image.delete()
        return JsonResponse({"status":'1'})
    except:
        return JsonResponse({"status":'2'})


def falls_images(request):
    images = Image.objects.all()
    return render(request,'image/falls_images.html',{"images":images})

mysite/templates/image/falls_images.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Images{% endblock %}
{% block content %}
<div class="container">
    <link rel="stylesheet" href="{% static 'css/mansory-style.css' %}" type="text/css">
    <div id="my-gallery-container">
        {% for image in images %}
        <div class="falls_item h200" data-order="{{image.id}}">
            <!--<img src="{{ image.image.url }}">-->
            <a href="javascript:void(0)" onclick="displayImage('{{image.user}}','{{image.title}}','{{image.image.url}}','{{image.description}}','{{request.get_host}}')">
                <img src="{{ image.image.url }}">
            </a>
            <p>{{ image.title }}</p>
        </div>
        {% endfor %}
    </div>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/mp.mansory.js' %}"></script>
<script src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
    jQuery(document).ready(function ( $ ) {
        $('#my-gallery-container').mpmansory({
            childrenClass:'falls_item', // default is a div
            columnClasses:'falls_padding',// add classes to items
            breakpoints:{
                lg:3,
                md:4,
                sm:6,
                xs:12
            },
            distributeBy:{order:false,height:false,attr:'data-order',attrOrder:'desc'},
            // default distribute by order,options=>order:true/false,heigth:true/false, attr=>'data-order', attrOrder=>'asc'/'desc'
        });
    });
    function displayImage(user,title,url,description,host) {
        layer.open({
            type:1,
            title:title,
            skin:'layui-layer-rim', // 加上边框
            area:["800px","600px"],
            content:'<div class="text-center"><img src="http://'+host+url+'"><p>发布者：'+user+'</p> </div><div style="margin-left: 10px">'+description+'</div> ',
        });

    }
</script>
{% endblock %}

mysite/templates/image/list_images.html
{% extends 'article/base.html' %}
{% load thumbnail %}
{% load staticfiles %}
{% block title %}images{% endblock %}
{% block content %}
<div>
    <button type="button" class="btn btn-primary btn-lg btn-block" onclick="addImage()">添加图片</button>
    <div style="margin-top: 10px">
        <table  class="table table-hover">
            <tr>
                <td>序号</td>
                <td>标题</td>
                <td>图片</td>
                <td>操作</td>
            </tr>
            {% for image in images %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ image.title }}</td>
                <!--<td>{{ image.image }}</td>-->
                <!--<td><img src="{{ image.image.url }}" width="300px" height="100px"> </td>-->
                {% thumbnail image.image "300x100" crop="center" as im %}
                <td><img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"></img> </td>
                {% endthumbnail %}
                <td><a name="delte" href="javascript:" onclick="del_image(this, {{ image.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left: 20px"></span>
                </a> </td>
            </tr>
            {% empty %}
            <p>还没有图片，请点击上面的按钮添加图片</p>
            {% endfor %}
        </table>
    </div>
    <!--{% include "paginator.html" %}-->
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
    function addImage() {
        var index = layer.open({
            type:1,
            skin:'layui-layer-demo',
            closeBtn:1,
            shift:2,
            shadeClose:true,
            title:'Add Image',
            area:['600px','440px'],
            content:'<div style="padding: 20px;"><p>请新增扩展名是.jpg或.png的网上照片地址</p><form><div class="form-group"><label for="phototitle" class="col-sm-2 control-label">标题</label><div class="col-sm-10"><input id="phototitle" type="text" class="form-control" style="margin-bottom: 5px;"></div></div><div class="form-group"><label for="photourl" class="col-sm-2 control-label">地址</label><div class="col-sm-10"><input id="photourl" style="margin-bottom: 5px" type="text" class="form-control"></div></div><div class="form-group"><label for="description" class="col-sm-2 control-label">描述</label><div class="col-sm-10"><textarea class="form-control" style="margin-bottom: 5px;" row="2" id="photodescription"></textarea></div></div><div class="form-group"><div class="col-sm-offset-2 col-sm-10"><input id="newphoto" type="button" class="btn btn-default" value="Add It"></div></div></form></div>',
            success:function () {
                $("#newphoto").on('click',function () {
                    var title =$('#phototitle').val();
                    var url = $('#photourl').val();
                    var description = $('#photodescription').val();
                    var photo = {"title":title,"url":url,"description":description};
                    $.ajax({
                        url:'{% url "image:upload_image" %}',
                        type: 'POST',
                        data: photo,
                        success:function (e) {
                            var status = e['status'];
                            if(status=="1"){
                                layer.close(index);
                                window.location.reload();
                            }else{
                                layer.msg("图片无法获取，请更换图片");
                            }

                        }
                    });
                });

            }
        });

    }

    function del_image(the,image_id) {
        var image_title = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
           type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            title:'删除图片',
            content:'<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+ image_title+'》</p></div>',
            btn:["确定","取消"],
            yes:function () {
               $.ajax({
                   url:'{% url "image:del_image" %}',
                   type:'POST',
                   data:{"image_id":image_id},
                   success:function (e) {
                       var status = e['status'];
                       if(status=="1"){
                           parent.location.reload();
                           layer.msg("has been deleted.");
                       }else{
                           layer.msg("删除失败");
                       }

                   },
               });

            }
        });

    }
</script>
{% endblock %}
<!--<div style="padding: 20px;"><p>请新增扩展名是.jpg或.png的网上照片地址</p>-->
    <!--<form><div class="form-group">-->
        <!--<label for="phototitle" class="col-sm-2 control-label">标题</label>-->
        <!--<div class="col-sm-10">-->
            <!--<input id="phototitle" type="text" class="form-control" style="margin-bottom: 5px;">-->
        <!--</div>-->
    <!--</div><div class="form-group">-->
        <!--<label for="photourl" class="col-sm-2 control-label">地址</label>-->
        <!--<div class="col-sm-10">-->
            <!--<input id="photourl" style="margin-bottom: 5px" type="text" class="form-control">-->
        <!--</div>-->
    <!--</div>-->
        <!--<div class="form-group">-->
            <!--<label for="description" class="col-sm-2 control-label">描述</label>-->
            <!--<div class="col-sm-10">-->
                <!--<textarea class="form-control" style="margin-bottom: 5px;" row="2" id="photodescription"></textarea>-->
            <!--</div>-->
        <!--</div>-->
        <!--<div class="form-group">-->
            <!--<div class="col-sm-offset-2 col-sm-10">-->
                <!--<input id="newphoto" type="button" class="btn btn-default" value="Add It">-->
            <!--</div></div></form></div>-->
