mysite/article/urls.py
from django.urls import path,re_path
from . import views,list_views

app_name = "article"

urlpatterns = [
    path("article-column/",views.article_column,name="article_column"),
    path("rename-column/",views.rename_article_column,name="rename_article_column"),
    path("del-column/",views.del_article_column,name="del_article_column"),
    path("article-post/",views.article_post, name="article_post"),
    path("article-list/",views.article_list,name='article_list'),
    re_path("article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$", views.article_detail, name='article_detail'),
    path("del-article/",views.del_article,name="del_article"),
    path("redit-article/<int:article_id>/",views.redit_article,name="redit_article"),
    path("list-article-titles/",list_views.article_titles,name="article_titles"),
    path("article-content/<int:id>/<slug:slug>/",list_views.article_detail,name="article_content"),
    path("list-article-titles/<username>/",list_views.article_titles,name="author_articles"),
    path("like-article/",list_views.like_article,name="like_article"),
    path("article-tag/",views.article_tag,name="article_tag"),
    path("del-article-tag/",views.del_article_tag,name="del_article_tag"),



]

mysite/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"  # 方式二需要加此项
urlpatterns = [
    path("", views.blog_title, name="blog_title"),
    path('<int:article_id>/', views.blog_article, name="blog_article"),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

# 为上传的图片配置url路径(1)
from django.conf import settings
from django.conf.urls.static import static
# 通用视图
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # 为了实现{% url 'blog:blog_title' %}的效果，需要在项目和应用两级的urls.py文件进行相应配置
    # path('blog/',include(('blog.urls', 'blog'), namespace='blog')),   # 方式一

    path('blog/', include('blog.urls', namespace='blog')),      # 方式二
    path('account/', include('account.urls', namespace='account')),
    path('article/',include('article.urls',namespace='article')),
    path('home/', TemplateView.as_view(template_name='home.html'),name='home'),
    path('image/', include('image.urls',namespace='image')),
    path('course/',include('course.urls',namespace='course')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/article/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.utils import timezone
from django.urls import reverse
from slugify import slugify


class ArticleTag(models.Model):
    """标签"""
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tag")
    tag = models.CharField(max_length=200)

    def __str__(self):
        return self.tag


class ArticleColumn(models.Model):
    """栏目"""
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticlePost(models.Model):
    """文章"""
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn,on_delete=models.CASCADE, related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    update = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User,related_name="articles_like", blank=True)   # 用户点赞功能
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag',blank=True)

    class Meta:
        ordering = ("-update",)         # 查询结果的排序
        index_together = (('id', 'slug'),)
        # 对数据库中这两个字段建立索引，后面会通过每篇文章的id和slug获取该文章对象，
        # 建立索引能够提高读取文章对象的速度

    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args,**kwargs)
        # 每个模型类都有一个save方法，对此方法进行重写，实现slug的赋值

    def get_absolute_url(self):
        return reverse("article:article_detail",args=[self.id, self.slug])
        # 获取谋篇文章对象的url

    def get_url_path(self):
        return reverse("article:article_content",args=[self.id,self.slug])


class Comment(models.Model):
    """文章评论"""
    article = models.ForeignKey(ArticlePost,on_delete=models.CASCADE,related_name="comments")
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by{0}on{1}".format(self.commentator.username,self.article)

mysite/article/forms.py
from django import forms
from .models import ArticleColumn,ArticlePost,Comment
from .models import ArticleTag


class ArticleColumnForm(forms.ModelForm):
    """栏目表单"""
    class Meta:
        model = ArticleColumn
        fields= ("column",)


class ArticlePostForm(forms.ModelForm):
    """文章表单"""
    class Meta:
        model = ArticlePost
        fields = ("title","body")


class CommentForm(forms.ModelForm):
    """评论表单"""
    class Meta:
        model = Comment
        fields = ("commentator","body",)


class ArticleTagForm(forms.ModelForm):
    """标签表单"""
    class Meta:
        model = ArticleTag
        fields=("tag",)

mysite/article/views.py
from django.shortcuts import render
from .models import ArticleColumn,ArticlePost
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from .forms import ArticleColumnForm,ArticlePostForm
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from .models import ArticleTag
from .forms import ArticleTagForm
import json


@login_required(login_url='/account/login/')
@csrf_exempt        # 解决提交表单中遇到csrf的问题
def article_column(request):
    """用户的栏目"""
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request,"article/column/article_column.html",{"columns":columns,'column_form':column_form})
    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id,column=column_name) # user_id 为以user作为外键
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user,column=column_name)
            return HttpResponse('1')


@login_required(login_url='account/login/')
@require_POST       # 保证此视图函数只通过POST方式提交数据
@csrf_exempt
def rename_article_column(request):
    """编辑栏目名称"""
    column_name = request.POST['column_name']
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def del_article_column(request):
    """删除栏目名称"""
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url="/account/login/")
@csrf_exempt
def article_post(request):
    """发布文章"""
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                # 作者自己 创建的栏目
                new_article.save()
                tags = request.POST["tags"]
                if tags:
                    for atag in json.loads(tags):
                        # json.loads()将JSON格式的数据转换为列表
                        tag = request.user.tag.get(tag=atag)
                        new_article.article_tag.add(tag)
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        article_tags = request.user.tag.all()
        # 作者自己创建的栏目  article_column 在ArticleColumn模型类中 related_name 属性的作用
        return render(request,"article/column/article_post.html",
                      {"article_post_form": article_post_form,"article_columns": article_columns,"article_tags":article_tags})


@login_required(login_url="/account/login/")
def article_list(request):
    """文章标题"""
    article_list = ArticlePost.objects.filter(author=request.user)
    # 根据查询到的文章对象article_list创建分页的实例对象，每页最多两个
    paginator = Paginator(article_list,2)
    page = request.GET.get('page')
    print(page)
    try:
        # page()是 Paginator对象的一个方法，用于得到指定页面的内容，值必须大于等于1的整数
        current_page = paginator.page(page)
        print(current_page)
        # object_list是Page对象的属性，能够得到该页所有的对象列表
        articles = current_page.object_list
    except PageNotAnInteger:  # 捕获异常请求页面数值不是整数
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:       # 请求页码数值为空，或在URL参数中没有page
        # paginator.num_pages返回的是页数，num_pages是Paginator对象的一个属性
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request,"article/column/article_list.html",{
        "articles":articles,"page":current_page})


@login_required(login_url="/account/login/")
def article_detail(request,id,slug):
    """文章内容页面"""
    article = get_object_or_404(ArticlePost,id=id,slug=slug)
    return render(request,"article/column/article_detail.html",{"article":article})


@login_required(login_url="/account/login/")
@require_POST
@csrf_exempt
def del_article(request):
    """删除文章"""
    article_id = request.POST["article_id"]
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url="/account/login/")
@csrf_exempt
def redit_article(request,article_id):
    """编辑文章"""
    if request.method == "GET":
        article_columns = request.user.article_column.all() # 用户所有的栏目
        article = ArticlePost.objects.get(id=article_id)    # 当前要编辑的文章
        this_article_form = ArticlePostForm(initial={"title":article.title})    # 初始化的文章表单
        this_article_column = article.column    # 当前文章所属的栏目
        return render(request,"article/column/redit_article.html",{
            "article":article,
            "article_columns":article_columns,
            "this_article_column":this_article_column,
            "this_article_form":this_article_form
        })
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column .get(id=request.POST["column_id"])
            redit_article.title = request.POST["title"]
            redit_article.body = request.POST["body"]
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")


@login_required(login_url='/account/login/')
@csrf_exempt
def article_tag(request):
    """标签模板返回和标签的添加"""
    if request.method == "GET":
        article_tags = ArticleTag.objects.filter(author= request.user)
        article_tag_form = ArticleTagForm()
        return render(request,"article/tag/tag_list.html",{
            "article_tags":article_tags,
            "article_tag_form":article_tag_form
        })
    if request.method == "POST":
        tag_post_form = ArticleTagForm(data=request.POST)
        if tag_post_form.is_valid():
            try:
                new_tag = tag_post_form.save(commit=False)
                new_tag.author = request.user
                new_tag.save()
                return HttpResponse("1")
            except:
                return HttpResponse("the data cannot be save")
        else:
            return HttpResponse("sorry,the form is not valid")


@login_required(login_url="/account/login/")
@require_POST
@csrf_exempt
def del_article_tag(request):
    tag_id = request.POST['tag_id']
    try:
        tag = ArticleTag.objects.get(id=tag_id)
        tag.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

mysite/templates/article/list/article_content.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}
{% block title %}articles detail {% endblock %}
{% block content %}
{% with total_likes=article.users_like.count users_like=article.users_like.all %}

<div class="container">
    <div class="col-md-9">
    <header>
        <h1>{{ article.title }}</h1>
       <p> <a href="{% url 'article:author_articles'  article.author.username %}">{{ article.author.username }}</a>
       <span style="margin-left: 20px" class="glyphicon glyphicon-thumbs-up">
           {{ total_likes }}like{{ total_likes | pluralize }}
           <!--当没有用户点赞或者超过一个用户点赞时，显示的是likes这种复数形式，如果只有一个用户点赞，
           则显示单数形式like | pluralize-->
       </span>
       <span style="margin-left: 20px">
           {{ total_views }}view{{ total_views | pluralize }}
       </span>
       </p>
        <p><span style="margin-right: 10px;"><strong>Tags:</strong></span>
        {{ article.article_tag.all | join:"," }}
         </p>
    </header>
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}"/>
    <div id="editormd-view">
        <!--<textarea id="append-test" style="display: none;">-->
<!--{{ article.body }}-->
        <!--</textarea>-->
        {{ article.body | markdown }}
    </div>
    <div>
        <p class="text-center">
            <a onclick="like_article({{ article.id }},'like')" href="#">
                <span class="glyphicon glyphicon-thumbs-up">like</span>
            </a>
            <a onclick="like_article({{ article.id }}, 'unlike')" href="#">
                <span style="margin-left: 15px" class="glyphicon glyphicon-thumbs-down">unlike</span>
            </a>
        </p>
    </div>
    <div>
        <p class="text-center"><strong>点赞本文的读者</strong></p>
        {% for user in article.users_like.all %}
        <p class="text-center">{{ user.username }}</p>
        {% empty %}
        <p class="text-center">还没有人对此文章表态</p>
        {% endfor %}
    </div>
        <hr>
        <div>
            <h3><span class="glyphicon glyphicon-bullhorn"></span>本文有{{ article.comments.count }}评论</h3>
            {% for comment in article.comments.all %}
            <div>
                <p><strong>{{ comment.commentator }}</strong>说：</p>
                <p style="margin-left: 40px;">{{ comment.body }}</p>
            </div>
            {% empty %}
            <p>没有评论！</p>
            {% endfor %}
            <h3><span class="glyphicon  glyphicon-send"></span>看文章，发表你的见解。 </h3>
            <form action="." method="post" class="form-horizontal" role="form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">评论员</label>
                    <div class="col-sm-10">
                        {{ comment_form.commentator }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">评论</label>
                    <div class="col-sm-10">
                        {{ comment_form.body }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <p><input type="submit" name="" value="发评论" class="btn btn-primary"></p>
                    </div>
                </div>
            </form>
        </div>

    </div>

    <div class="col-md-3">
        <p class="text-center"><h3>最受欢迎的文章</h3></p>
        <ol>
            {% for article_rank  in most_viewed %}
            <li>
                <a href="{{ article_rank.get_url_path }}">{{ article_rank.title }}</a>
            </li>
            {% endfor %}
        </ol>
        <hr>
        <p class="text-center"><h3>最新文章</h3></p>
        {% latest_articles 4 %}
        <hr>
        <p class="text-center"><h3>最多评论的文章</h3></p>
        <ul>
            <!--把自定义标签所得到的对象赋值给一个变量-->
            {% most_commented_articles as most_comments %}
            {% for comment_article in  most_comments %}
            <li>
                <a href="{{ comment_article.get_url_path }}">{{ comment_article.title }}</a>

            </li>
            {% endfor %}
        </ul>
        <hr>
        <p class="text-center"><h3>推荐相似文章</h3></p>
        {% for similar in similar_articles %}
        <p><a href="{{ similar.get_url_path }}">{{ similar.title }}</a> </p>
        {% empty%}
        <p>Sorry,没有相似文章</p>
        {% endfor %}
    </div>
</div>


<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'editor/lib/marked.min.js' %}"></script>
<script src="{% static 'editor/lib/prettify.min.js' %}"></script>
<script src="{% static 'editor/lib/raphael.min.js' %}"></script>
<script src="{% static 'editor/lib/underscore.min.js' %}"></script>
<script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
<script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
<script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
<script src="{% static 'editor/editormd.js' %}"></script>
<script src="{% static 'js/layer.js' %}"></script>

<script type="text/javascript">
    function like_article(id,action) {
        $.ajax({
           url:"{% url 'article:like_article' %}",
            type:"POST",
            data:{"id":id,"action":action},
            success:function (e) {
               if(e=="1"){
                   layer.msg("感谢点赞");
                   window.location.reload();
               }else{
                   layer.msg("我会继续努力");
                   window.location.reload();
               }

            },
        });
    }
    $(function () {
        editormd.markdownToHTML("editormd-view",{
            htmlDecode:'style,script,iframe',
            emoji:true,
            taskList:true,
            tex:true,
            flowchart:true,
            sequenceDiagram:true,
        });
    });

</script>
{% endwith %}
{% endblock %}

mysite/templates/article/list/article_titles.html
{% extends "base.html" %}
{% load article_tags %}
{% block title %}articles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>阅读塑造人生，技术改变世界！</h1>
    <p>这里已经有{% total_articles %}篇文章供你阅读</p>
</div>

<div class="container">
    {% for article in articles %}
    <div class="list-group">
        <a href="{{ article.get_url_path }}" class="list-group-item active">
            <h4 class="list-group-item-heading">{{ article.title }}</h4>
        </a>

        <p class="list-group-item-text">
            <a href="{% url 'article:author_articles' article.author.username %}">
                作者：{{ article.author.username }}
            </a>
        </p>
            <p class="list-group-item-text">概要：{{ article.body|slice:'70'| linebreaks }}</p>

    </div>
    {% endfor %}
    {% include "paginator.html" %}
</div>
{% endblock %}

mysite/templates/article/list/author_articles.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}
{% block title %}articles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>细节决定成败，坚持做好每一件事！</h1>
</div>
<div class="container">
    <div class="col-md-8">
        {% for article in articles %}
        <div class="list-group">
            <a href="{{ article.get_url_path }}" class="list-group-item active">
                <h4 class="list-group-item-heading">{{ article.title }}</h4>
            </a>
            <p class="list-group-item-text">作者：
                <a href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a>
            </p>
            <p class="list-group-item-text">概要：
                {{ article.body | slice:'70'| linebreaks }}
            </p>
        </div>
        {% endfor %}
        {% include "paginator.html" %}
    </div>
    <div class="col-md-4">
        <div>
            {% if userinfo.photo %}
            <img src="/media/{{ userinfo.photo | striptags }}" class="img-circle" id="my_photo" name="user_face" style="width: 200px;">
            {% else %}
            <img name="user_face" src="{% static 'img/newton.jpg' %}" class="img-circle" id="my_photo" style="width: 200px;">
            {% endif %}
        </div>
        <div>
            <p>{{ users.username }}</p>
            <p>共发表文章{% author_total_articles  users %}篇</p>
        {% if userinfo %}
            <p>{{ userinfo.company }}</p>
            <p>{{ userinfo.aboutme }}</p>
        {% else %}
            <p>这个人太懒，什么也没有留下。</p>
        {% endif %}
        </div>
    </div>

</div>

{% endblock %}

mysite/templates/article/list/latest_articles.html
<ul>
    {% for article in latest_articles %}
    <li>
        <a href="{{ article.get_url_path }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>